server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/authenticate,/api/v1/register
        - id: bookmark
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/bookmarks/**
        - id: annotation
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/annotations/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "OPTIONS"
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace
